[package]
name = "picky_feed"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
reqwest = { version = "0.12.24", features = ["blocking", "cookies"] }
serde = { version = "1.0.228", features = ["serde_derive"] }
toml = "0.9.7"
